// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2d6cf16c-94bb-409a-8e2c-01bc274922e4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_2ERa8SNfC",
    "aws_user_pools_web_client_id": "6qsfl5hq402u67jrlm7f8ls396",
    "oauth": {}
};

/* auto generated - to be deleted later
const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:05d16876-e073-445f-b3ed-9e77c65ed248",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_SfGSa9O0M",
    "aws_user_pools_web_client_id": "1bspga5eejcv57h4qf3133pikv",
    "oauth": {}
};
*/

export default awsmobile;
